### ISSUE TITLE
FAQ TODO

### ISSUE THREAD

**Issue by q66** [void-ppc64/documentation#4]
This will stay open and track things that do not need specific solutions in packages/live images but should be added into our FAQ (https://docs.voidlinux-ppc.org/faq/index.html)

Useful resources that could be reviewed and integrated:

https://wiki.ubuntu.com/PowerPCFAQ
https://wiki.debian.org/PowerPC/FAQ
https://wiki.gentoo.org/wiki/PPC/FAQ

As always, feel free to add into this or even work on these (and submit pull requests for this repo).

# Current

- [x] Serial console setup for live and production environment
- [x] WiFi firmware installation on Apple PowerPC hardware with Broadcom `b43`
- [ ] Sound setup on Apple PowerPC hardware
- [x] Why is my clock being reset to 1970? I have an old Apple with a dead backup battery
- [x] Disabling https in NTP to allow machines with 1970 date to sync even without working certs
- [ ] Battery indicator enablement
- [ ] Suspend/resume

# Done

**Comment by goosnarrggh** [comment]
On some PowerMac machines, the snd-powermac kernel module may not be automatically detected at boot time. If the user experiences this, then they may need to manually load that module by adding an appropriate new .conf file to /etc/modules-load.d/

I am still running into what appears to be trouble with pusleaudio failing to initialize itself, even after taking steps to ensure that the kernel module is being loaded; after a reboot I am still finding myself needing to shutdown and restart pulseaudio deamon manually. Still looking into a better way to automate this.

**Comment by hamishmb** [comment]
Could we add fan control to this list? At least on my iBook G4 it works, but I can't see the RPM or change the fan curve, it seems.
